definitions:
  db.ListData-db_WeekPlan:
    properties:
      data:
        description: 列表
        items:
          $ref: '#/definitions/db.WeekPlan'
        type: array
      total:
        description: 总数
        type: integer
    type: object
  db.TimePeroid:
    properties:
      end:
        description: 结束时间戳
        type: string
      start:
        description: 开始时间戳
        type: string
    type: object
  db.WeekPlan:
    properties:
      createdAt:
        description: 数据库的创建时间，时间戳，
        type: integer
      data:
        description: 保存的天数
        type: string
      enable:
        description: |-
          是否禁用
          0: 禁用
          1: 启用
        type: integer
      id:
        description: 数据库ID
        type: string
      name:
        description: 名称
        type: string
      peroids:
        description: 是一个 RecordTime 的 JSON 数组
        type: string
      updatedAt:
        description: 数据库的更新时间
        type: integer
    type: object
  internal.Error:
    properties:
      detail:
        description: 详细信息
      phrase:
        description: 简短信息
        type: string
    type: object
  internal.IDResult-int64:
    properties:
      id:
        description: 数据库 ID
        type: integer
    type: object
  internal.RowResult:
    properties:
      row:
        description: 行数
        type: integer
    type: object
  tasks.tasks:
    properties:
      id:
        description: 流的唯一标识
        type: string
      startCallback:
        description: 开始录像回调
        maxLength: 255
        type: string
      stopCallback:
        description: 停止录像回调
        maxLength: 255
        type: string
    required:
    - id
    - startCallback
    - stopCallback
    type: object
  weekplans.patchReq:
    properties:
      data:
        description: 附加的数据
        type: string
      enable:
        description: |-
          是否禁用
          0: 禁用
          1: 启用
        enum:
        - 0
        - 1
        type: integer
      name:
        description: 名称
        maxLength: 32
        type: string
      peroids:
        description: 一周的时间数组
        items:
          items:
            $ref: '#/definitions/db.TimePeroid'
          type: array
        maxItems: 7
        minItems: 1
        type: array
    required:
    - peroids
    type: object
  weekplans.postReq:
    properties:
      data:
        description: 附加的数据
        type: string
      enable:
        description: |-
          是否禁用，默认是 1
          0: 禁用
          1: 启用
        enum:
        - 0
        - 1
        type: integer
      name:
        description: 名称
        maxLength: 32
        type: string
      peroids:
        description: 一周的时间数组
        items:
          items:
            $ref: '#/definitions/db.TimePeroid'
          type: array
        maxItems: 7
        minItems: 1
        type: array
    required:
    - name
    - peroids
    type: object
info:
  contact: {}
  title: 接口文档
  version: 1.0.0
paths:
  /week_plans:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 条件
        in: body
        name: data
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal.Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Error'
      security:
      - ApiKeyAuth: []
      summary: 批量删除
      tags:
      - 周计划
    get:
      parameters:
      - description: 创建时间，时间戳，范围匹配，CreatedAt >= CreatedAtAfter
        in: query
        minimum: 0
        name: afterCreatedAt
        type: integer
      - description: 更新时间，时间戳，范围匹配，UpdateAt >= UpdatedAtAfter
        in: query
        minimum: 0
        name: afterUpdatedAt
        type: integer
      - description: 创建时间，时间戳，范围匹配，CreatedAt < CreatedBefore
        in: query
        name: beforeCreatedAt
        type: integer
      - description: 更新时间，时间戳，范围匹配，UpdateAt < UpdatedAtBefore
        in: query
        name: beforeUpdatedAt
        type: integer
      - description: 条数，小于 1 不匹配
        in: query
        minimum: 1
        name: count
        type: integer
      - description: 是否禁用，精确匹配
        enum:
        - 0
        - 1
        in: query
        name: enable
        type: integer
      - description: 名称，模糊匹配
        in: query
        maxLength: 32
        name: name
        type: string
      - description: 偏移，小于 0 不匹配
        in: query
        minimum: 0
        name: offset
        type: integer
      - description: 排序，"column [desc]"
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.ListData-db_WeekPlan'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Error'
      summary: 列表
      tags:
      - 周计划
    post:
      consumes:
      - application/json
      parameters:
      - description: 数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/weekplans.postReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal.IDResult-int64'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Error'
      summary: 添加
      tags:
      - 周计划
  /week_plans/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: WeekPlan.ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Error'
      summary: 删除
      tags:
      - 周计划
    get:
      parameters:
      - description: WeekPlan.ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.WeekPlan'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/internal.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Error'
      summary: 详情
      tags:
      - 周计划
    patch:
      consumes:
      - application/json
      parameters:
      - description: WeekPlan.ID
        in: path
        name: id
        required: true
        type: string
      - description: 数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/weekplans.patchReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal.RowResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Error'
      summary: 修改
      tags:
      - 周计划
  /week_plans/{id}/tasks:
    delete:
      consumes:
      - application/json
      parameters:
      - description: WeekPlan.ID
        in: path
        name: id
        required: true
        type: string
      - description: 自定义的任务 ID 数组
        in: body
        name: data
        required: true
        schema:
          items:
            type: string
          type: array
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Error'
      summary: 删除任务
      tags:
      - 周计划
    put:
      consumes:
      - application/json
      parameters:
      - description: WeekPlan.ID
        in: path
        name: id
        required: true
        type: string
      - description: 任务数组
        in: body
        name: data
        required: true
        schema:
          items:
            $ref: '#/definitions/tasks.tasks'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal.IDResult-int64'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Error'
      summary: 添加任务
      tags:
      - 周计划
swagger: "2.0"
