definitions:
  db.Record:
    properties:
      createTime:
        description: 时间戳
        type: integer
      deleteTime:
        description: 删除时间戳
        type: integer
      duration:
        description: 时长，单位秒
        type: number
      isDeleted:
        description: 软删除
        type: integer
      name:
        description: minio 标识
        type: string
      size:
        description: 大小，字节
        type: integer
      stream:
        description: stream
        type: string
    type: object
  internal.Error:
    properties:
      detail:
        description: 详细信息
      phrase:
        description: 简短信息
        type: string
    type: object
  records.postReq:
    properties:
      deleteTime:
        description: 删除时间
        minimum: 0
        type: integer
      duration:
        description: 时长
        minimum: 1
        type: number
      name:
        description: minio 的标识
        maxLength: 40
        type: string
      size:
        description: 大小
        minimum: 1
        type: integer
      stream:
        description: stream
        maxLength: 64
        type: string
      time:
        description: 创建时间
        minimum: 1
        type: integer
    required:
    - deleteTime
    - duration
    - name
    - size
    - stream
    - time
    type: object
  util.GORMList-db_Record:
    properties:
      data:
        description: 列表
        items:
          $ref: '#/definitions/db.Record'
        type: array
      total:
        description: 总数
        type: integer
    type: object
info:
  contact: {}
  title: 接口文档
  version: 1.0.0
paths:
  /records:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 条件
        in: body
        name: ids
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal.Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Error'
      security:
      - ApiKeyAuth: []
      summary: 批量删除
      tags:
      - 云端录像
    get:
      parameters:
      - description: 大于创建时间戳，比较
        in: query
        name: afterTime
        type: integer
      - description: 小于删除时间戳 ，比较
        in: query
        name: beforeTime
        type: integer
      - description: 条数，小于 1 不匹配
        in: query
        minimum: 1
        name: count
        type: integer
      - description: 偏移，小于 0 不匹配
        in: query
        minimum: 0
        name: offset
        type: integer
      - description: 排序，"column [desc]"
        in: query
        name: order
        type: string
      - description: stream ，精确
        in: query
        maxLength: 64
        name: stream
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.GORMList-db_Record'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Error'
      summary: 列表
      tags:
      - 云端录像
    post:
      consumes:
      - application/json
      parameters:
      - description: 数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/records.postReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Error'
      summary: 添加
      tags:
      - 云端录像
  /records/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 主键
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Error'
      summary: 删除
      tags:
      - 云端录像
    get:
      parameters:
      - description: Record.Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.Record'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/internal.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Error'
      summary: 详情
      tags:
      - 云端录像
swagger: "2.0"
